spring:
    datasource:
        url: jdbc:mysql://hanghae-order-mysql:3306/order
        username: root
        password: rootpassword
    jpa:
        hibernate:
            ddl-auto: create
#    cloud:
#        openfeign:
#            client:
#                config:
#                    FeignUserInfoAccessor:
#                        url: http://hanghae-auth-user-network:8080/v1/user

