spring:
    datasource:
        url: jdbc:mysql://hanghae-like-cart-mysql:3306/like-cart
        username: root
        password: rootpassword
    jpa:
        hibernate:
            ddl-auto: update
