package hanghae99.plus2.team3.hanghaeorder.domain.order.mock

import hanghae99.plus2.team3.hanghaeorder.domain.payment.Payment
import hanghae99.plus2.team3.hanghaeorder.domain.payment.infrastructure.PaymentRepository
import hanghae99.plus2.team3.hanghaeorder.infrastructure.payment.entity.PaymentEntity
import java.util.*
import java.util.concurrent.atomic.AtomicLong

class FakePaymentRepositoryImpl : PaymentRepository {
        private val autoGeneratedId : AtomicLong = AtomicLong(0)
         val paymentRequests : MutableList<PaymentEntity> =
             Collections.synchronizedList(mutableListOf<PaymentEntity>())


        override fun save(payment: Payment): Payment {
            val entity = PaymentEntity(
                id = autoGeneratedId.incrementAndGet(),
                paymentNum = payment.paymentNum,
                paymentVendor = payment.paymentVendor,
                paymentAmount = payment.paymentAmount,
                success = payment.success,
                paymentResultCode = payment.paymentResultCode,
            )
            paymentRequests.add(entity)
            return payment.copy(id = entity.id)
        }


    }
