jays:
    hanghae:
        journey:
            profile: local

spring:
    datasource:
        url: jdbc:mysql://hanghae-customer-mysql:3306/customer
        username: root
        password: rootpassword
    jpa:
        hibernate:
            ddl-auto: update
