package hanghae99.plus2.team3.commerce.jaehyun.product.mock

import hanghae99.plus2.team3.commerce.jaehyun.product.domain.Product
import hanghae99.plus2.team3.commerce.jaehyun.product.domain.ProductRepository
import hanghae99.plus2.team3.commerce.jaehyun.product.infrastructure.ProductEntity
import java.util.*
import java.util.concurrent.atomic.AtomicLong

class FakeProductRepositoryImpl(
    private val productMemoryRepository: ProductMemoryRepository,
) : ProductRepository {
    override fun save(product: Product) : Product {
        return productMemoryRepository.save(product)
    }
}

class ProductMemoryRepository {
    private val autoGeneratedId = AtomicLong(0)
    private val products = Collections.synchronizedList(mutableListOf<ProductEntity>())

    fun save(product: Product): Product {
        val entity = ProductEntity(
            id = autoGeneratedId.incrementAndGet(),
            name = product.name,
            price = product.price,
            quantity = product.quantity,
            sellerId = product.sellerId,
            shopId = product.shopId,
            category = product.category,
        )
        products.add(entity)
        return product.copy(id = entity.id)
    }
}
