SET
    REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE ORDER_ENTITY;
ALTER TABLE ORDER_ENTITY
    ALTER COLUMN ID RESTART WITH 1;

TRUNCATE TABLE ORDER_ITEM_ENTITY;
ALTER TABLE ORDER_ITEM_ENTITY
    ALTER COLUMN ID RESTART WITH 1;

TRUNCATE TABLE PAYMENT_ENTITY;
ALTER TABLE PAYMENT_ENTITY
    ALTER COLUMN ID RESTART WITH 1;


INSERT INTO ORDER_ENTITY (MESSAGE,RECEIVER_ADDRESS1,RECEIVER_ADDRESS2,RECEIVER_NAME,RECEIVER_PHONE,RECEIVER_ZIP_CODE,ORDER_NUM,ORDER_STATUS,USER_ID,ID) VALUES
('부재시 경비실에 맡겨주세요','서울시 강남구','역삼동','홍길동','010-1234-5678','12345','orderNum-1','ORDERED',1,999);
INSERT INTO ORDER_ITEM_ENTITY (DELIVERY_STATUS,ORDER_ID,PRODUCT_ID,PRODUCT_PRICE,QUANTITY,ID) VALUES
('BEFORE_PAYMENT',999,1,2000,1,999),
('BEFORE_PAYMENT',999,2,3000,1,998);





