package hanghae99.plus2.team3.commerce.jaehyun.market.mock

import hanghae99.plus2.team3.commerce.jaehyun.market.domain.Market
import hanghae99.plus2.team3.commerce.jaehyun.market.domain.MarketRepository
import hanghae99.plus2.team3.commerce.jaehyun.market.infrastructure.MarketEntity
import java.util.*
import java.util.concurrent.atomic.AtomicLong

class FakeMarketRepositoryImpl(
    private val marketMemoryRepository: MarketMemoryRepository
) : MarketRepository {
    override fun save(market: Market): Market {
        return marketMemoryRepository.save(market)
    }
}

class MarketMemoryRepository {
    private val autoGeneratedId = AtomicLong(0)
    private val markets = Collections.synchronizedList(mutableListOf<MarketEntity>())

    fun save(market: Market): Market {
        val entity = MarketEntity(
            id = autoGeneratedId.incrementAndGet(),
            name = market.name,
            sellerId = market.sellerId,
        )
        markets.add(entity)
        return market.copy(id = entity.id)
    }
}
