package hanghae99.plus2.team3.commerce.jaehyun.shop.mock

import hanghae99.plus2.team3.commerce.jaehyun.seller.infrastructure.SellerEntity
import hanghae99.plus2.team3.commerce.jaehyun.shop.domain.Shop
import hanghae99.plus2.team3.commerce.jaehyun.shop.domain.ShopRepository
import hanghae99.plus2.team3.commerce.jaehyun.shop.infrastructure.ShopEntity
import java.util.*
import java.util.concurrent.atomic.AtomicLong

class FakeShopRepositoryImpl(
    private val shopMemoryRepository: ShopMemoryRepository
) : ShopRepository {
    override fun save(shop: Shop): Shop {
        return shopMemoryRepository.save(shop)
    }
}

class ShopMemoryRepository {
    private val autoGeneratedId = AtomicLong(0)
    private val shops = Collections.synchronizedList(mutableListOf<ShopEntity>())

    fun save(shop: Shop): Shop {
        val entity = ShopEntity(
            id = autoGeneratedId.incrementAndGet(),
            name = shop.name,
            seller = SellerEntity(shop.seller),
        )
        shops.add(entity)
        return shop.copy(id = entity.id)
    }
}
